# Generated by Django 3.0.6 on 2020-05-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_1', models.CharField(max_length=528)),
                ('movie_2', models.CharField(max_length=528)),
                ('movie_3', models.CharField(max_length=528)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('index', models.IntegerField()),
                ('budget', models.BigIntegerField()),
                ('genres', models.CharField(max_length=528)),
                ('homepage', models.CharField(max_length=528)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=528)),
                ('original_language', models.CharField(max_length=528)),
                ('original_title', models.CharField(max_length=528)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('production_companies', models.TextField()),
                ('production_countries', models.TextField()),
                ('release_data', models.DateField()),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('spoken_languages', models.TextField()),
                ('status', models.CharField(max_length=528)),
                ('tagline', models.CharField(max_length=528)),
                ('title', models.CharField(max_length=528)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('cast', models.TextField()),
                ('crew', models.TextField()),
                ('director', models.CharField(max_length=528)),
                ('time_created', models.TimeField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]